### ISSUE TITLE
非常好扩展, 可惜不能选清晰度

### ISSUE THREAD

**Issue by ddzzkunye** [EZ118/BiliChrome#1]
非常好扩展, 可惜不能选清晰度. 
另外能把稍后再看移到侧边吗

**Comment by EZ118** [comment]
非常感谢！
目前由于B站的API对于请求有限制，自由调节清晰度需要鉴权，因此现在没能实现。刚才我提交了一次更改，加入了高画质的切换功能，可以在播放器中切换。经过对API的测试，发现在请求高画质（1080P）视频源时，无需鉴权。
对于稍后再看功能，我会在之后的更新中对这方面进行调节。

**Comment by EZ118** [comment]
> 可以切换画质吗? 没发现啊
扩展商店最新版本里有两个地方可以切换：
1. 播放器右上角按钮“HD”（扩展商店最新版图标显示不出来）
2. 我的>扩展选项>默认1080P画质>保存设置
