### ISSUE TITLE
扩展打包为zip 与 直接加载压缩的扩展

### ISSUE THREAD

**Issue by ddzzkunye** [EZ118/BiliChrome#2]
发布打包zip时, 如果可选的话,  
zip内部不要包含文件夹`BiliChrome-2.0.0`, 而是直接使用插件的根目录,  
这样可以直接加载压缩的扩展而无需解压.

**Comment by EZ118** [comment]
好主意，从下一个release开始，我会额外打包一个可以直接加载的zip文件
