### ISSUE TITLE
Chrome报错，无法刷出任何东西

### ISSUE THREAD

**Issue by Coldvvater** [EZ118/BiliChrome#3]
2.1.2和3.0版本的chrome插件一直报错，无法刷出任何东西，调出UI一直转圈，2.1.1无此问题。
![70562dfc4924a05a70748e8e99562db3](https://github.com/user-attachments/assets/ed1dcbcb-2621-492d-8b88-1884bad62da4)

**Comment by EZ118** [comment]
我认为是2.1.1版本的manifest.json里包含以下代码使扩展正常运行
```json
    "host_permissions": [
        "*://*.bilibili.com/*"
    ],
```
后续版本被修改为明确的链接。可能是这样导致的。
目前在我这里(edge/chrome)是可以运行的，可以尝试修改manifest.json为上述内容再试。
希望尽快回复!

**Comment by EZ118** [comment]
7

**Comment by EZ118** [comment]
点错了😅

**Comment by Coldvvater** [comment]
> 我认为是2.1.1版本的manifest.json里包含以下代码使扩展正常运行
> 
> ```json
>     "host_permissions": [
>         "*://*.bilibili.com/*"
>     ],
> ```
> 
> 后续版本被修改为明确的链接。可能是这样导致的。 目前在我这里(edge/chrome)是可以运行的，可以尝试修改manifest.json为上述内容再试。 希望尽快回复!

果然是这样，修改了就好了。另外，我发现排版有很多错位，比如你截图里首页横向有三行我这只有两行，还有个人页里用户名称竖着显示等等。

**Comment by EZ118** [comment]
视频列表的纵列数是按照窗口大小来定的，目前给视频卡片的宽限定了绝对的宽度。如果想要增加列数，只能缩放网页或调整窗口大小。
我正在尝试修复错位问题。
